Update CohortMembership create view and serializer to accept list uploads
academic-innovation/mogc-partnerships pull request #30
Opened 2023-12-21 17:55 UTC by aphilipharrell

### Part 1/2 of https://github.com/academic-innovation/frontend-app-mogc-partners/issues/53

- Update `CohortMembershipCreateView` to add cohort and user to context
- Add `CohortMembershipListSerializer` to handle bulk inserts
- Update `CohortMembershipSerializer` to use list serializer if `data` is a list
- Remove `catalog` endpoints now that they are fully replace in frontend app

2024-02-07 15:07 UTC, aphilipharrell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Partner portal improvements discovered during AAUM pilot](https://trello.com/c/Im60O5yf/750-partner-portal-improvements-discovered-during-aaum-pilot)

2024-02-15 19:48 UTC, michaelwheeler requested changes
Hey @aphilipharrell sorry it's taken so long to get this reviewed. I added a few questions and suggestions, but hopefully nothing too outrageous.

2024-02-15 19:48 UTC, michaelwheeler commented on tests/test_views.py
> +        assert response.status_code == 201
Should we also assert that the expected number of memberships were created?

2024-02-15 19:48 UTC, michaelwheeler commented on mogc_partnerships/views.py
> +    def perform_create(self, serializer):
Does `perform_create` even need an implementation here? I think this is the same as what is inherited.

2024-02-15 19:48 UTC, michaelwheeler commented on mogc_partnerships/views.py
> +        return {"cohort": cohort, "user": user}
I'm not seeing how `user` is being referenced in the serializers. Does it need to be included in the context?

2024-02-26 19:20 UTC, michaelwheeler requested changes
Sorry @aphilipharrell just one more question/comment to address.

2024-02-26 19:20 UTC, michaelwheeler commented on mogc_partnerships/serializers.py
> +        ).all()
Should this also filter the QuerySet to only include memberships associated with `cohort`?

Also, I think the `.all()` is not necessary.

2024-02-28 13:50 UTC, michaelwheeler approved these changes
Thanks @aphilipharrell 🎉

2024-05-08 13:15 UTC, merged