Deactivation flow QA follow up
academic-innovation/mogc-partnerships pull request #42
Opened 2024-10-02 16:03 UTC by aphilipharrell

Corrects issues with the deactivation flow:
- Incorrect return values used in edX unenroll action
- Filter serialized enrollments on user offerings by active
- Move enrollment object update to _after_ the edX compat call (Django was returning early from this method unexpectedly?)
- Check for deactivation in update request before going through unenroll flow (may not have had any unintended consequences outside of my own local testing while manually manipulating DB data)
- Return 403 on `CohortOfferingListView` if user is not a manager or they have no active memberships
- Add receiver for unenrollment in `apps.py` for when a learner unenrolls from the learner portal

2024-10-02 17:23 UTC, aphilipharrell commented on mogc_partnerships/views.py
> -        eligible_enrollment_records.update(is_active=False)
Oh - I expected this result to be static here, this must have been changing the value of `eligible_enrollment_records` and after the update there weren't eligible records anymore.

2024-10-02 19:22 UTC, michaelwheeler requested changes

2024-10-02 19:22 UTC, michaelwheeler commented on mogc_partnerships/views.py
> +        ).values_list("offering_id", flat=True)
We can use the `active` method of our custom manager here.

```suggestion
        context["enrollments"] = self.request.user.enrollment_records.active().values_list(
            "offering_id", flat=True
        )
```

2024-10-03 14:42 UTC, michaelwheeler approved these changes
Good thinking using the unenrollment event 🧠 please merge when ready!

2024-10-08 17:23 UTC, merged